### ISSUE TITLE
[PE-D][Tester A] FABook allows different users to have the same phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-2/tp#143]
Added 3 users with 3 different names but with the same phone number. It might not not make sense to allow different contacts to have the same phone number.

![image.png](https://raw.githubusercontent.com/CJun1039/ped/main/files/760005ff-c037-402c-8154-859aa2096334.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: CJun1039/ped#3

**Comment by eugenetayyj** [comment]
## Conclusion
Only disallow if name and hp is same, else its alright.
