### ISSUE TITLE
[PE-D][Tester C] Find by name command bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T10-2/tp#148]
Using `find n/Dav` does not correctly yield the result for `David Li` in the contact even though the user guide stated that `Jack` will match `Jackson`.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dexter-sim/ped#3

**Comment by eugenetayyj** [comment]
## Conclusion 
Bug
