### ISSUE TITLE
[PE-D][Tester C] Sync Command UI Bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T10-2/tp#156]
Sync command successfully removes meeting but does not reflect in the GUI immediately. There is a need to click on the specific contact in the list for the GUI to refresh.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dexter-sim/ped#7

**Comment by shauneang** [comment]
Is this a bug? should we fix this? solution: change how sync is done currently and change it to go through set person
